### ISSUE TITLE
Snapshot missing for RetroArch and Adrenaline

### ISSUE THREAD

**Issue by Vitty85** [GrapheneCt/ThreadOptimizer#5]
The R+L+Square combo is not working while using RetroArch or Adrenaline, so it's impossible to take snapshot of those application's threads.

**Comment by simonizer2409** [comment]
RetroArch isn't multithreaded - no performance gains. And Adrenaline doesn't even use the Vita's CPU to begin with - so this wouldn't even be possible... at all.

**Comment by Vitty85** [comment]
I got it, I tried even with Netflix app and still impossible to take snapshot, but maybe again not multithread app.

**Comment by simonizer2409** [comment]
Never used Netflix, but you probably want to use this in combination with PSVshell, so you can set the CPU frequency and keep track of CPU load. Makes most sense to try this out with games, which could still perform better -> higher framerate.

But in my experience, you don't get any performance gains in many games. Many games already run with a stable framerate of 30/60fps without this - that is, if you overclock the CPU. And for the games I did try it with, there was no advantage running it with Thread Optimizer - at least not in using more cores, didn't change thread priorities. In some cases the bottleneck seems to be the GPU and more CPU power won't grant more performance. Your experience may prove me wrong, only tested it with 5 games.

**Comment by Vitty85** [comment]
I tested with fifa 20 mod and the game loads correctly after I arranged the thread cpu schedule, but I cannot really say if there was a sensible increase of performance or not, I will try to investigate with other games too.

--
Inviato da iPhone
