### ISSUE TITLE
Possibly not capturing all threads

### ISSUE THREAD

**Issue by justalex95** [GrapheneCt/ThreadOptimizer#9]
In assassins creed, I captured a profile at the start of messing around with it and it had a networking related thread and a thread called Worker thread #1. I accidentally deleted this profile. I can capture the network related thread again but the Worker thread I've never managed to capture and I cant replicate it.

There might be a 2nd worker thread as well which might explain why speed ups are completely non existent for AC

**Comment by GrapheneCt** [comment]
Thread capture is accumulative. That means that all threads created during application runtime are captured. When you actually make snapshot, it offloads current accumulated information to the file. If thread did not get captured again it simply means it was not created by application up to the moment of capturing snapshot.
